### ISSUE TITLE
An icon name doesn't exist

### ISSUE THREAD

**Issue by jjaimealeman** [boussadjra/vueye#4]
Hi there.

I really like this project.

I came across a few errors.

`rendering chunks (1)...[unocss] failed to load icon "i-carbon-exclamation"`

![screenshot1](https://i.imgur.com/ZjNnUm6.png)

![screenshot2](https://i.imgur.com/EWTqCFG.png)

### Versions

```sh
└─>node -v && npm -v && pnpm -v         
v16.17.0
8.15.0
7.9.5
```

**Comment by boussadjra** [comment]
Hi, that's great pleasure to see someone liking my project, I fixed the issue please clone the project again or just remove `i-carbon-exclamation` from `src\pages\components\icons.vue`

**Comment by jjaimealeman** [comment]
So the first error from above `rendering chunks (1)...[unocss] failed to load icon "i-carbon-exclamation"` was not repeated, so cool! 👍 I noticed you removed it from `icons.vue`, simple solution - lol.

However the second error persists:
![error](https://i.imgur.com/TNiCuPG.png)

**Comment by boussadjra** [comment]
what did you run as command? since I don't get that error when I run `pnpm run dev`

**Comment by jjaimealeman** [comment]
`pnpm run dev` has no error.
![screenshot1](https://i.imgur.com/EhsGVQr.png)

`pnpm run build` is the one that produces the error.

Here is a video/cast output for you https://asciinema.org/a/h2Jk1dyMCUYPchh3YUiXU7YtD

**Comment by boussadjra** [comment]
I think there's something went wrong with vite-ssg plugin, I'll create an issue there. thank you

**Comment by boussadjra** [comment]
I've found the where the issue comes from, I've a wrong element name ` <class i-carbon-copy size="1em" />` in icons page, it's a stupid typo, I just changed to `span` and the error is gone, I gonna push the changes

**Comment by jjaimealeman** [comment]
How did you find `<class i-carbon-copy size="1em" />` was the cause? Am impressed! :D

By the way, `pnpm run build` ran with out issue.

**Comment by boussadjra** [comment]
The weakmap used in this tool takes a valid html element name like `div`, `span` ..., `class` is not a valid one, please don't forget to star the project if you've not done that yet
